{ pkgs, ... }:

{
  vim = {
    startPlugins = [
      pkgs.vimPlugins.alpha-nvim
      pkgs.vimPlugins.plenary-nvim # required dependency
    ];

    pluginRC.alpha = ''
            local alpha = require("alpha")
            local dashboard = require("alpha.themes.dashboard")

      -- Kartoza logo highlight groups (generated by term2alpha from catimg output)
      -- Wrapped in a function so they can be re-applied after colorscheme changes
      -- (colorscheme loading calls 'highlight clear' which wipes custom groups)
      local function setup_t2a_highlights()
      vim.api.nvim_set_hl(0, "T2A244557", { bg="#244557" })
      vim.api.nvim_set_hl(0, "T2A4a3716", { bg="#4a3716" })
      vim.api.nvim_set_hl(0, "T2A4a8fb5", { bg="#569FC6" })
      vim.api.nvim_set_hl(0, "T2Ace9a3e", { bg="#DF9E2F" })
      vim.api.nvim_set_hl(0, "T2Aeeb248", { bg="#DF9E2F" })
      vim.api.nvim_set_hl(0, "T2A182f3c", { fg="#182f3c" })
      vim.api.nvim_set_hl(0, "T2A1b3543", { fg="#1b3543" })
      vim.api.nvim_set_hl(0, "T2A1b354353a0c9", { fg="#1b3543", bg="#569FC6" })
      vim.api.nvim_set_hl(0, "T2A1d3947", { fg="#1d3947" })
      vim.api.nvim_set_hl(0, "T2A214051244557", { fg="#214051", bg="#244557" })
      vim.api.nvim_set_hl(0, "T2A21405154a2cc", { fg="#214051", bg="#569FC6" })
      vim.api.nvim_set_hl(0, "T2A214152264a5d", { fg="#214152", bg="#264a5d" })
      vim.api.nvim_set_hl(0, "T2A223b47", { fg="#223b47" })
      vim.api.nvim_set_hl(0, "T2A223b4754a2cc", { fg="#223b47", bg="#569FC6" })
      vim.api.nvim_set_hl(0, "T2A224354", { fg="#224354" })
      vim.api.nvim_set_hl(0, "T2A244659", { fg="#244659" })
      vim.api.nvim_set_hl(0, "T2A25485b", { fg="#25485b" })
      vim.api.nvim_set_hl(0, "T2A292929", { fg="#292929" })
      vim.api.nvim_set_hl(0, "T2A2929298a8b8b", { fg="#292929", bg="#8a8b8b" })
      vim.api.nvim_set_hl(0, "T2A2c2c2c", { fg="#2c2c2c" })
      vim.api.nvim_set_hl(0, "T2A2c2c2c898a8a", { fg="#2c2c2c", bg="#8A8B8B" })
      vim.api.nvim_set_hl(0, "T2A2d2d2d898a8a", { fg="#2d2d2d", bg="#8A8B8B" })
      vim.api.nvim_set_hl(0, "T2A2d2d2d8a8b8b", { fg="#2d2d2d", bg="#8a8b8b" })
      vim.api.nvim_set_hl(0, "T2A2f5a72", { fg="#2f5a72" })
      vim.api.nvim_set_hl(0, "T2A2f5a7254a2cc", { fg="#2f5a72", bg="#569FC6" })
      vim.api.nvim_set_hl(0, "T2A305c74", { fg="#305c74" })
      vim.api.nvim_set_hl(0, "T2A32627b", { fg="#32627b" })
      vim.api.nvim_set_hl(0, "T2A33647e", { fg="#33647e" })
      vim.api.nvim_set_hl(0, "T2A33647e3e7999", { fg="#33647e", bg="#3e7999" })
      vim.api.nvim_set_hl(0, "T2A356681", { fg="#356681" })
      vim.api.nvim_set_hl(0, "T2A424242", { fg="#424242" })
      vim.api.nvim_set_hl(0, "T2A434444", { fg="#434444" })
      vim.api.nvim_set_hl(0, "T2A4382a454a2cc", { fg="#569FC6", bg="#569FC6" })
      vim.api.nvim_set_hl(0, "T2A443314", { fg="#443314" })
      vim.api.nvim_set_hl(0, "T2A444444", { fg="#444444" })
      vim.api.nvim_set_hl(0, "T2A444545", { fg="#444545" })
      vim.api.nvim_set_hl(0, "T2A453417daa341", { fg="#453417", bg="#DF9E2F" })
      vim.api.nvim_set_hl(0, "T2A4789ad509bc3", { fg="#569FC6", bg="#569FC6" })
      vim.api.nvim_set_hl(0, "T2A4789ad54a2cc", { fg="#569FC6", bg="#569FC6" })
      vim.api.nvim_set_hl(0, "T2A498eb3", { fg="#569FC6" })
      vim.api.nvim_set_hl(0, "T2A4f99c1498eb3", { fg="#569FC6", bg="#569FC6" })
      vim.api.nvim_set_hl(0, "T2A503c18eeb248", { fg="#503c18", bg="#DF9E2F" })
      vim.api.nvim_set_hl(0, "T2A509bc353a1cb", { fg="#569FC6", bg="#569FC6" })
      vim.api.nvim_set_hl(0, "T2A509bc354a2cc", { fg="#569FC6", bg="#569FC6" })
      vim.api.nvim_set_hl(0, "T2A519dc654a2cc", { fg="#569FC6", bg="#569FC6" })
      vim.api.nvim_set_hl(0, "T2A525252", { fg="#525252" })
      vim.api.nvim_set_hl(0, "T2A5253538a8b8b", { fg="#525353", bg="#8a8b8b" })
      vim.api.nvim_set_hl(0, "T2A529ec74a8fb5", { fg="#569FC6", bg="#569FC6" })
      vim.api.nvim_set_hl(0, "T2A529ec754a2cc", { fg="#569FC6", bg="#569FC6" })
      vim.api.nvim_set_hl(0, "T2A529fc954a2cc", { fg="#569FC6", bg="#569FC6" })
      vim.api.nvim_set_hl(0, "T2A53a0c954a2cc", { fg="#569FC6", bg="#569FC6" })
      vim.api.nvim_set_hl(0, "T2A54a2cc264a5d", { fg="#569FC6", bg="#264a5d" })
      vim.api.nvim_set_hl(0, "T2A54a2cc3b728f", { fg="#569FC6", bg="#3b728f" })
      vim.api.nvim_set_hl(0, "T2A54a2cc3e7999", { fg="#569FC6", bg="#3e7999" })
      vim.api.nvim_set_hl(0, "T2A54a2cc498eb3", { fg="#569FC6", bg="#569FC6" })
      vim.api.nvim_set_hl(0, "T2A54a2cc509bc3", { fg="#569FC6", bg="#569FC6" })
      vim.api.nvim_set_hl(0, "T2A54a2cc53a0c9", { fg="#569FC6", bg="#569FC6" })
      vim.api.nvim_set_hl(0, "T2A54a2cc53a1cb", { fg="#569FC6", bg="#569FC6" })
      vim.api.nvim_set_hl(0, "T2A54a2cc54a2cc", { fg="#569FC6", bg="#569FC6" })
      vim.api.nvim_set_hl(0, "T2A5a5b5b8a8b8b", { fg="#5a5b5b", bg="#8a8b8b" })
      vim.api.nvim_set_hl(0, "T2A5b441b", { fg="#5b441b" })
      vim.api.nvim_set_hl(0, "T2A5b441b54a2cc", { fg="#5b441b", bg="#569FC6" })
      vim.api.nvim_set_hl(0, "T2A606060", { fg="#606060" })
      vim.api.nvim_set_hl(0, "T2A6060608a8b8b", { fg="#606060", bg="#8a8b8b" })
      vim.api.nvim_set_hl(0, "T2A6d6d6d", { fg="#6d6d6d" })
      vim.api.nvim_set_hl(0, "T2A6e6f6f", { fg="#6e6f6f" })
      vim.api.nvim_set_hl(0, "T2A6f5321", { fg="#6f5321" })
      vim.api.nvim_set_hl(0, "T2A737373", { fg="#737373" })
      vim.api.nvim_set_hl(0, "T2A747575", { fg="#747575" })
      vim.api.nvim_set_hl(0, "T2A7475758a8b8b", { fg="#747575", bg="#8a8b8b" })
      vim.api.nvim_set_hl(0, "T2A775924", { fg="#775924" })
      vim.api.nvim_set_hl(0, "T2A7b5c25", { fg="#7b5c25" })
      vim.api.nvim_set_hl(0, "T2A7b7c7c898a8a", { fg="#7b7c7c", bg="#8A8B8B" })
      vim.api.nvim_set_hl(0, "T2A7b7c7c8a8b8b", { fg="#7b7c7c", bg="#8a8b8b" })
      vim.api.nvim_set_hl(0, "T2A808080", { fg="#808080" })
      vim.api.nvim_set_hl(0, "T2A848585294f63", { fg="#848585", bg="#294f63" })
      vim.api.nvim_set_hl(0, "T2A858686818282", { fg="#858686", bg="#8A8B8B" })
      vim.api.nvim_set_hl(0, "T2A8586868a8b8b", { fg="#858686", bg="#8a8b8b" })
      vim.api.nvim_set_hl(0, "T2A866428", { fg="#866428" })
      vim.api.nvim_set_hl(0, "T2A866428eeb248", { fg="#866428", bg="#DF9E2F" })
      vim.api.nvim_set_hl(0, "T2A878888272727", { fg="#878888", bg="#272727" })
      vim.api.nvim_set_hl(0, "T2A8888888a8b8b", { fg="#888888", bg="#8a8b8b" })
      vim.api.nvim_set_hl(0, "T2A898a8a", { fg="#8A8B8B" })
      vim.api.nvim_set_hl(0, "T2A8a8b8b", { fg="#8a8b8b" })
      vim.api.nvim_set_hl(0, "T2A8a8b8b244353", { fg="#8a8b8b", bg="#244353" })
      vim.api.nvim_set_hl(0, "T2A8a8b8b272727", { fg="#8a8b8b", bg="#272727" })
      vim.api.nvim_set_hl(0, "T2A8a8b8b294f63", { fg="#8a8b8b", bg="#294f63" })
      vim.api.nvim_set_hl(0, "T2A8a8b8b707171", { fg="#8a8b8b", bg="#707171" })
      vim.api.nvim_set_hl(0, "T2A8a8b8b7d7e7e", { fg="#8a8b8b", bg="#7d7e7e" })
      vim.api.nvim_set_hl(0, "T2A8a8b8b818282", { fg="#8a8b8b", bg="#8A8B8B" })
      vim.api.nvim_set_hl(0, "T2A8a8b8b898a8a", { fg="#8a8b8b", bg="#8A8B8B" })
      vim.api.nvim_set_hl(0, "T2A8a8b8b8a8b8b", { fg="#8a8b8b", bg="#8a8b8b" })
      vim.api.nvim_set_hl(0, "T2A9a732ed49e40", { fg="#9a732e", bg="#DF9E2F" })
      vim.api.nvim_set_hl(0, "T2A9b742fedb147", { fg="#9b742f", bg="#DF9E2F" })
      vim.api.nvim_set_hl(0, "T2Aa77d32eeb248", { fg="#a77d32", bg="#DF9E2F" })
      vim.api.nvim_set_hl(0, "T2Aaa7f33", { fg="#aa7f33" })
      vim.api.nvim_set_hl(0, "T2Abd8d39", { fg="#DF9E2F" })
      vim.api.nvim_set_hl(0, "T2Abd8d39ab8033", { fg="#DF9E2F", bg="#ab8033" })
      vim.api.nvim_set_hl(0, "T2Ac7943c", { fg="#DF9E2F" })
      vim.api.nvim_set_hl(0, "T2Acc983d", { fg="#DF9E2F" })
      vim.api.nvim_set_hl(0, "T2Acc983dedb147", { fg="#DF9E2F", bg="#DF9E2F" })
      vim.api.nvim_set_hl(0, "T2Acf9b3eeeb248", { fg="#DF9E2F", bg="#DF9E2F" })
      vim.api.nvim_set_hl(0, "T2Ae7ac45eeb248", { fg="#DF9E2F", bg="#DF9E2F" })
      vim.api.nvim_set_hl(0, "T2Ae9ae46d49e40", { fg="#DF9E2F", bg="#DF9E2F" })
      vim.api.nvim_set_hl(0, "T2Ae9ae46eeb248", { fg="#DF9E2F", bg="#DF9E2F" })
      vim.api.nvim_set_hl(0, "T2Aeaaf474a3716", { fg="#DF9E2F", bg="#4a3716" })
      vim.api.nvim_set_hl(0, "T2Aeaaf47dfa743", { fg="#DF9E2F", bg="#DF9E2F" })
      vim.api.nvim_set_hl(0, "T2Aedb147daa341", { fg="#DF9E2F", bg="#DF9E2F" })
      vim.api.nvim_set_hl(0, "T2Aedb147eeb248", { fg="#DF9E2F", bg="#DF9E2F" })
      vim.api.nvim_set_hl(0, "T2Aeeb248ab8033", { fg="#DF9E2F", bg="#ab8033" })
      vim.api.nvim_set_hl(0, "T2Aeeb248ca973d", { fg="#DF9E2F", bg="#DF9E2F" })
      vim.api.nvim_set_hl(0, "T2Aeeb248ce9a3e", { fg="#DF9E2F", bg="#DF9E2F" })
      vim.api.nvim_set_hl(0, "T2Aeeb248d9a241", { fg="#DF9E2F", bg="#DF9E2F" })
      vim.api.nvim_set_hl(0, "T2Aeeb248dfa743", { fg="#DF9E2F", bg="#DF9E2F" })
      vim.api.nvim_set_hl(0, "T2Aeeb248edb147", { fg="#DF9E2F", bg="#DF9E2F" })
      vim.api.nvim_set_hl(0, "T2Aeeb248eeb248", { fg="#DF9E2F", bg="#DF9E2F" })
      end

      setup_t2a_highlights()
      vim.api.nvim_create_autocmd("ColorScheme", {
        callback = setup_t2a_highlights,
      })

      -- Kartoza logo header (generated by: catimg -H 30 kartoza-logo.png | term2alpha)
      dashboard.section.header.val = {
        [[         ▄▄         ]],
        [[      ▄▄▄▄▄▄▄▄      ]],
        [[     ▄▄▄▀  ▀▄▄▄     ]],
        [[     ▄▄▄    ▄▄▄     ]],
        [[    ▄▄▄▄▄▄▄▄▄▄▄▄    ]],
        [[  ▄▄▄▄▀▄▄▄▀▀▀▄▄▄▄▄  ]],
        [[ ▄▄▀   ▀▀▄▄▄    ▀▄▄ ]],
        [[ ▄▄▄   ▄▄▄▄▄▄   ▄▄▄ ]],
        [[ ▀▄▄▄▄▄▄▄▀▀▄▄▄▄▄▄▄▀ ]],
        [[    ▀▀▀      ▀▀▀    ]],
      }

      -- Per-line highlight specs (generated by term2alpha, byte-indexed)
      local charhl = {
          { { "T2A25485b", 9, 12 }, { "T2A244659", 12, 15 }},
          { { "T2A33647e", 6, 10 }, { "T2A33647e3e7999", 9, 11 }, { "T2A54a2cc3e7999", 9, 13 }, { "T2A54a2cc54a2cc", 12, 17 }, { "T2A529fc954a2cc", 15, 20 }, { "T2A53a0c954a2cc", 18, 23 }, { "T2A54a2cc54a2cc", 21, 25 }, { "T2A54a2cc3b728f", 24, 27 }, { "T2A356681", 27, 30 }},
          { { "T2A1b3543", 5, 9 }, { "T2A1b354353a0c9", 8, 10 }, { "T2A54a2cc53a0c9", 8, 12 }, { "T2A54a2cc54a2cc", 11, 13 }, { "T2A519dc654a2cc", 11, 14 }, { "T2A32627b", 14, 17 }, { "T2A2f5a72", 19, 23 }, { "T2A2f5a7254a2cc", 22, 24 }, { "T2A509bc354a2cc", 22, 26 }, { "T2A509bc353a1cb", 25, 27 }, { "T2A54a2cc53a1cb", 25, 28 }, { "T2A1d3947", 28, 31 }},
          { { "T2A244557", 5, 7 }, { "T2A214051244557", 5, 9 }, { "T2A21405154a2cc", 8, 10 }, { "T2A54a2cc54a2cc", 8, 12 }, { "T2A54a2cc498eb3", 11, 13 }, { "T2A4f99c1498eb3", 11, 14 }, { "T2A4a8fb5", 18, 20 }, { "T2A529ec74a8fb5", 18, 22 }, { "T2A529ec754a2cc", 21, 23 }, { "T2A54a2cc54a2cc", 21, 25 }, { "T2A54a2cc264a5d", 24, 26 }, { "T2A214152264a5d", 24, 27 }},
          { { "T2A775924", 4, 7 }, { "T2A5b441b", 7, 11 }, { "T2A5b441b54a2cc", 10, 12 }, { "T2A4382a454a2cc", 10, 15 }, { "T2A54a2cc54a2cc", 13, 16 }, { "T2A305c74", 16, 19 }, { "T2A424242", 19, 22 }, { "T2A8a8b8b", 22, 25 }, { "T2A8a8b8b", 25, 29 }, { "T2A8a8b8b244353", 28, 32 }, { "T2A8a8b8b294f63", 31, 33 }, { "T2A848585294f63", 31, 34 }, { "T2A6d6d6d", 34, 37 }, { "T2A444444", 37, 40 }},
          { { "T2A4a3716", 2, 4 }, { "T2Aeaaf474a3716", 2, 6 }, { "T2Aeaaf47dfa743", 5, 7 }, { "T2Aeeb248dfa743", 5, 9 }, { "T2Aeeb248eeb248", 8, 10 }, { "T2Ae9ae46eeb248", 8, 12 }, { "T2Ae9ae46d49e40", 11, 13 }, { "T2A9a732ed49e40", 11, 14 }, { "T2A223b47", 14, 18 }, { "T2A223b4754a2cc", 17, 19 }, { "T2A4789ad54a2cc", 17, 21 }, { "T2A4789ad509bc3", 20, 22 }, { "T2A54a2cc509bc3", 20, 23 }, { "T2A224354", 23, 26 }, { "T2A808080", 26, 29 }, { "T2A898a8a", 29, 32 }, { "T2A8a8b8b", 32, 36 }, { "T2A8a8b8b8a8b8b", 35, 37 }, { "T2A2929298a8b8b", 35, 40 }, { "T2A5253538a8b8b", 38, 43 }, { "T2A8586868a8b8b", 41, 45 }, { "T2A858686818282", 44, 46 }, { "T2A8a8b8b818282", 44, 48 }, { "T2A8a8b8b272727", 47, 49 }, { "T2A878888272727", 47, 50 }},
          { { "T2Ace9a3e", 1, 3 }, { "T2Aeeb248ce9a3e", 1, 5 }, { "T2Aeeb248eeb248", 4, 7 }, { "T2Ac7943c", 7, 10 }, { "T2A182f3c", 13, 16 }, { "T2A498eb3", 16, 19 }, { "T2Acc983d", 19, 23 }, { "T2Acc983dedb147", 22, 24 }, { "T2Aeeb248edb147", 22, 27 }, { "T2A9b742fedb147", 25, 28 }, { "T2A747575", 32, 36 }, { "T2A7475758a8b8b", 35, 37 }, { "T2A8a8b8b8a8b8b", 35, 39 }, { "T2A8a8b8b7d7e7e", 38, 41 }},
          { { "T2Aeeb248", 1, 3 }, { "T2Ae7ac45eeb248", 1, 6 }, { "T2Aeeb248eeb248", 4, 7 }, { "T2Aaa7f33", 7, 10 }, { "T2Abd8d39", 13, 17 }, { "T2Abd8d39ab8033", 16, 18 }, { "T2Aeeb248ab8033", 16, 20 }, { "T2Aeeb248eeb248", 19, 21 }, { "T2Aedb147eeb248", 19, 23 }, { "T2Aedb147daa341", 22, 24 }, { "T2A453417daa341", 22, 25 }, { "T2A6e6f6f", 25, 28 }, { "T2A737373", 28, 31 }, { "T2A606060", 34, 38 }, { "T2A6060608a8b8b", 37, 39 }, { "T2A8a8b8b8a8b8b", 37, 42 }, { "T2A8888888a8b8b", 40, 43 }},
          { { "T2A866428", 1, 5 }, { "T2A866428eeb248", 4, 6 }, { "T2Aa77d32eeb248", 4, 9 }, { "T2Aeeb248eeb248", 7, 11 }, { "T2Aeeb248d9a241", 10, 14 }, { "T2Aeeb248ca973d", 13, 17 }, { "T2Aeeb248edb147", 16, 20 }, { "T2Aeeb248eeb248", 19, 21 }, { "T2Acf9b3eeeb248", 19, 24 }, { "T2A503c18eeb248", 22, 25 }, { "T2A6f5321", 25, 28 }, { "T2A2c2c2c", 28, 32 }, { "T2A2c2c2c898a8a", 31, 33 }, { "T2A2d2d2d898a8a", 31, 35 }, { "T2A2d2d2d8a8b8b", 34, 36 }, { "T2A7b7c7c8a8b8b", 34, 38 }, { "T2A7b7c7c898a8a", 37, 39 }, { "T2A8a8b8b898a8a", 37, 41 }, { "T2A8a8b8b707171", 40, 44 }, { "T2A8a8b8b7d7e7e", 43, 47 }, { "T2A8a8b8b8a8b8b", 46, 51 }, { "T2A5a5b5b8a8b8b", 49, 52 }, { "T2A525252", 52, 55 }},
          { { "T2A7b5c25", 4, 7 }, { "T2A775924", 7, 10 }, { "T2A443314", 10, 13 }, { "T2A292929", 19, 22 }, { "T2A444545", 22, 25 }, { "T2A434444", 25, 28 }},
      }

      dashboard.section.header.opts = {
        position = "center",
        hl = charhl,
      }

      -- Menu buttons
      dashboard.section.buttons.val = {
        dashboard.button("n", "  New file", ":ene | startinsert<CR>"),
        dashboard.button("f", "  Find file", ":Telescope find_files<CR>"),
        dashboard.button("r", "  Recent files", ":Telescope oldfiles<CR>"),
        dashboard.button("s", "  Restore session", ":SessionManager load_last_session<CR>"),
        dashboard.button("q", "  Quit", ":qa<CR>")
      }

      -- Footer
      dashboard.section.footer.val = {"Kartoza NeoVim"}

      -- Layout with header
      dashboard.config.layout = {
        {type = "padding", val = 0},
        dashboard.section.header,
        {type = "padding", val = 1},
        {
          type = "group",
          val = dashboard.section.buttons.val,
          opts = {
            position = "center",
            spacing = 0
          }
        },
        {type = "padding", val = 0},
        dashboard.section.footer,
      }

      dashboard.opts.opts.noautocmd = true
      alpha.setup(dashboard.opts)

      -- Force alpha to show on startup unless a file was passed as argument
      vim.api.nvim_create_autocmd("VimEnter", {
        callback = function()
          -- Re-apply T2A highlights after colorscheme/theme has loaded
          setup_t2a_highlights()
          if vim.fn.argc() == 0 then
            -- Close any buffers that other plugins may have opened, then show alpha
            vim.schedule(function()
              if vim.bo.filetype ~= "alpha" then
                require("alpha").start(false)
              end
            end)
          end
        end,
      })
    '';
  };
}
