{ ... }:
{
  imports = [
    ./alpha.nix
    ./conform.nix
    ./debugger.nix
    ./fzf.nix
    ./filetree.nix
    ./floaterm.nix
    ./git.nix
    ./hardtime.nix
    ./languages.nix
    ./lsp.nix
    ./lualine.nix
    ./luasnip.nix
    ./notify.nix
    ./notes.nix
    ./nvzone-typr.nix
    ./minimap.nix
    ./oil.nix
    ./projects.nix
    ./snacks
    ./telescope.nix
    ./terminal.nix
    ./treesitter.nix
    ./undoTree.nix
    ./yanky.nix
    ./colorizer.nix
    ./mini-nvim.nix
    ./image.nix
    ./markdown.nix
    ./python.nix
  ];
}
